### ISSUE TITLE
more user defined configuration in **retention-redis.cfg**

### ISSUE THREAD

**Issue by andyxning** [shinken-monitoring/mod-retention-redis#2]
I have recently use this module to retain the scheduler daemon info. However, I find that the only argument i can specific is the server name of the Redis, even the port number and db argument can not be specified. Can we just make the arguments in `retention-redis.cfg` comform with the `__init__` function's params in [line 391](https://github.com/andymccurdy/redis-py/blob/master/redis/client.py#L391)

**Comment by andyxning** [comment]
Since this has not been answered for a long time, i have forked the repo and add some new features. [Here is the address](https://github.com/andyxning/mod-retention-redis)

**Comment by naparuba** [comment]
Are you interested into being the maintener of this module? You are now
familiar with our dev ways and you are using this module it in production :)

If so I can add you in the shinken-montoring group so you can commit on
this repository, and I can give you the lead on the redis module on
shinken.io ^^

**Comment by andyxning** [comment]
Yes, i would like to be a Collaborator of this module. :)

++++++
Ning Xie


2015-05-11 15:21 GMT+08:00 Gabès Jean <notifications@github.com>:

**Comment by vaxvms** [comment]
Thanks @andyxning 

I've cherry-pickend some of your commits.

I've not cherry-picked the ley_prefix commit. If you want to use the same redis instance for several shinken instance, your should use separe db.
